# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NHlYYTy2H2Vo_CPmub1iwkFqtGCSlTUR
"""

!pip install datasets kagglehub -q

import kagglehub
path = kagglehub.dataset_download("ishanikathuria/handwritten-signature-datasets")
print("Path to dataset files:", path)

import os
os.kill(os.getpid(), 9)

import torch
print("PyTorch version:", torch.__version__)
print("GPU Active:", torch.cuda.is_available())

import os
import glob
import random
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import torchvision.models as models
import torchvision.transforms as transforms
from PIL import Image

print("="*60)
print("🚀 STEP 1: INITIALIZING ENVIRONMENT & CONFIGURATIONS")
print("="*60)

# Explicitly using your exact verified KaggleHub dataset path
dataset_root = "/root/.cache/kagglehub/datasets/ishanikathuria/handwritten-signature-datasets/versions/3"
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# --- HYPERPARAMETERS AND CONFIGURATIONS DICTIONARY ---
config = {
    "Dataset Root Path": dataset_root,
    "Target Device": device,
    "Model Backbone": "ResNet-18 (Pre-trained on ImageNet)",
    "Embedding Dimension": 128,
    "Batch Size": 32,
    "Learning Rate": 0.0001,
    "Optimizer": "Adam",
    "Loss Function": "Contrastive Loss",
    "Contrastive Margin": 2.0,
    "Training Epochs": 5,
    "Image Resize Dimensions": (224, 224)
}

# Print the active configuration parameters
for key, value in config.items():
    print(f"🔹 {key}: {value}")

print("\n"+"="*60)
print("📦 STEP 2: PARSING DATASET AND GENERATING PAIRS")
print("="*60)

class KaggleSiameseDataset(Dataset):
    def __init__(self, root_dir, transform=None):
        self.root_dir = root_dir
        self.transform = transform
        self.pairs = []
        self.labels = []

        # --- DYNAMIC LOOKUP LAYER TO PREVENT PATH ERRORS ---
        possible_paths = [
            os.path.join(root_dir, "cedar", "CEDAR"),
            os.path.join(root_dir, "cedar", "cedar"),
            os.path.join(root_dir, "CEDAR"),
            os.path.join(root_dir, "cedar")
        ]

        cedar_path = None
        for path_option in possible_paths:
            if os.path.exists(path_option) and any(fname.endswith('.png') for fname in os.listdir(path_option)):
                cedar_path = path_option
                break

        if cedar_path is None:
            # Fallback assignment to root if no subfolders match criteria
            cedar_path = root_dir

        print(f"[Data Loader] Target verification directory resolved to: {cedar_path}")

        positive_count = 0
        negative_count = 0

        # Person IDs range from 1 to 55 in the CEDAR dataset
        for person_id in range(1, 56):
            genuine_pattern = os.path.join(cedar_path, f"original_{person_id}_*.png")
            forged_pattern = os.path.join(cedar_path, f"forgeries_{person_id}_*.png")

            genuine_imgs = sorted(glob.glob(genuine_pattern))
            forged_imgs = sorted(glob.glob(forged_pattern))

            if len(genuine_imgs) == 0:
                continue

            # Create Positive Pairs (Genuine + Genuine) -> Label = 0
            for i in range(len(genuine_imgs)):
                for j in range(i + 1, min(i + 5, len(genuine_imgs))):
                    self.pairs.append((genuine_imgs[i], genuine_imgs[j]))
                    self.labels.append(0.0)
                    positive_count += 1

            # Create Negative Pairs (Genuine + Forged) -> Label = 1
            for i in range(min(len(genuine_imgs), 15)):
                for j in range(min(len(forged_imgs), 15)):
                    self.pairs.append((genuine_imgs[i], forged_imgs[j]))
                    self.labels.append(1.0)
                    negative_count += 1

        print(f"✅ Data Extraction Complete!")
        print(f"   ├── Total Positive Pairs (Genuine-Genuine): {positive_count}")
        print(f"   ├── Total Negative Pairs (Genuine-Forged): {negative_count}")
        print(f"   └── Total Dataset Signature Pairs: {len(self.pairs)}")

        if len(self.pairs) == 0:
            raise RuntimeError(f"🚨 Critical Failure: 0 images matched standard naming pattern inside {cedar_path}. Verify folder directory contents.")

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, idx):
        img1_path, img2_path = self.pairs[idx]
        img1 = Image.open(img1_path).convert("RGB")
        img2 = Image.open(img2_path).convert("RGB")
        label = torch.tensor(self.labels[idx], dtype=torch.float32)

        if self.transform:
            img1 = self.transform(img1)
            img2 = self.transform(img2)

        return img1, img2, label

# Transform pipeline
data_transforms = transforms.Compose([
    transforms.Resize(config["Image Resize Dimensions"]),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

train_dataset = KaggleSiameseDataset(dataset_root, transform=data_transforms)
train_loader = DataLoader(train_dataset, batch_size=config["Batch Size"], shuffle=True)

print("\n"+"="*60)
print("🧠 STEP 3: BUILDING MODEL ARCHITECTURE & COUNTING PARAMETERS")
print("="*60)

class SiameseResNet(nn.Module):
    def __init__(self, embedding_dim=128):
        super(SiameseResNet, self).__init__()
        # Loads a pre-trained ResNet-18 base network model
        self.backbone = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)
        num_features = self.backbone.fc.in_features
        self.backbone.fc = nn.Identity()  # Strip final classification layer

        # Custom Fully Connected head for vector embedding
        self.fc_head = nn.Sequential(
            nn.Linear(num_features, 512),
            nn.ReLU(inplace=True),
            nn.Dropout(p=0.3),
            nn.Linear(512, embedding_dim)
        )

    def forward_once(self, x):
        output = self.backbone(x)
        output = self.fc_head(output)
        return output

    def forward(self, input1, input2):
        output1 = self.forward_once(input1)
        output2 = self.forward_once(input2)
        return output1, output2

model = SiameseResNet(embedding_dim=config["Embedding Dimension"]).to(device)

# --- PARAMETER COUNT CALCULATION ---
total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print("✅ Network Structural Summary Loaded Successfully!")
print(f"   ├── Total Network Parameters: {total_params:,}")
print(f"   └── Trainable Network Parameters: {trainable_params:,}")

print("\n"+"="*60)
print("🧪 STEP 4: LOSS FUNCTION & OPTIMIZER DEFINITION")
print("="*60)

class ContrastiveLoss(nn.Module):
    def __init__(self, margin=2.0):
        super(ContrastiveLoss, self).__init__()
        self.margin = margin

    def forward(self, output1, output2, label):
        euclidean_distance = nn.functional.pairwise_distance(output1, output2)
        loss_contrastive = torch.mean(
            (1 - label) * torch.pow(euclidean_distance, 2) +
            (label) * torch.pow(torch.clamp(self.margin - euclidean_distance, min=0.0), 2)
        )
        return loss_contrastive

criterion = ContrastiveLoss(margin=config["Contrastive Margin"])
optimizer = optim.Adam(model.parameters(), lr=config["Learning Rate"])
print(f"✅ Loss Objective and Optimization Rules compiled into memory.")

print("\n"+"="*60)
print("🏋️ STEP 5: RUNNING THE DEEP LEARNING TRAINING LOOP")
print("="*60)

total_steps = len(train_loader)
for epoch in range(config["Training Epochs"]):
    model.train()
    running_loss = 0.0

    print(f"\n🎬 Starting Epoch [{epoch+1}/{config['Training Epochs']}]")
    print("-" * 40)

    for batch_idx, (img1, img2, label) in enumerate(train_loader):
        img1, img2, label = img1.to(device), img2.to(device), label.to(device)

        optimizer.zero_grad()
        output1, output2 = model(img1, img2)
        loss = criterion(output1, output2, label)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        # Print update status milestones every 20 batches
        if (batch_idx + 1) % 20 == 0 or (batch_idx + 1) == total_steps:
            print(f"⏱️ Progress: Batch [{batch_idx+1}/{total_steps}] ── Current Batch Loss: {loss.item():.4f}")

    epoch_avg_loss = running_loss / total_steps
    print(f"📉 Epoch [{epoch+1}/{config['Training Epochs']}] Finished ── Average Loss: {epoch_avg_loss:.4f}")

print("\n"+"="*60)
print("💾 STEP 6: SAVING MODEL WEIGHTS FOR DEPLOYMENT")
print("="*60)
torch.save(model.state_dict(), "siamese_resnet_signature.pth")
print("🎉 Success! Your trained model weights file is saved as 'siamese_resnet_signature.pth'.")
print("You are ready to proceed with user-interface construction or manual inference verification tests.")

