# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NHlYYTy2H2Vo_CPmub1iwkFqtGCSlTUR
"""

!pip install datasets kagglehub -q

import kagglehub
path = kagglehub.dataset_download("ishanikathuria/handwritten-signature-datasets")
print("Path to dataset files:", path)

import os
os.kill(os.getpid(), 9)

import torch
print("PyTorch version:", torch.__version__)
print("GPU Active:", torch.cuda.is_available())

# ============================================================
# OFFLINE HANDWRITTEN SIGNATURE VERIFICATION
# Siamese ResNet-18 + Contrastive Loss
# Dataset: BHSig260 Bengali/Hindi
# ============================================================

# ============================================================
# STEP 0: IMPORTS
# ============================================================

import os
import glob
import random
import re
import numpy as np

import torch
import torch.nn as nn
import torch.optim as optim

from torch.utils.data import Dataset, DataLoader

import torchvision.models as models
import torchvision.transforms as transforms

from PIL import Image


# ============================================================
# STEP 1: REPRODUCIBILITY
# ============================================================

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)


# ============================================================
# STEP 2: CONFIGURATION
# ============================================================

print("=" * 70)
print("🚀 STEP 1: INITIALIZING ENVIRONMENT & CONFIGURATIONS")
print("=" * 70)


# ------------------------------------------------------------
# KaggleHub dataset path
# ------------------------------------------------------------

dataset_root = (
    "/root/.cache/kagglehub/datasets/"
    "ishanikathuria/handwritten-signature-datasets/"
    "versions/3"
)


device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)


config = {

    "Dataset Root Path": dataset_root,

    "Target Device": device,

    "Model Backbone":
        "ResNet-18 (Pre-trained on ImageNet)",

    "Embedding Dimension":
        128,

    "Batch Size":
        32,

    "Learning Rate":
        0.0001,

    "Weight Decay":
        1e-4,

    "Optimizer":
        "Adam",

    "Loss Function":
        "Contrastive Loss",

    "Contrastive Margin":
        2.0,

    "Training Epochs":
        5,

    "Image Resize Dimensions":
        (224, 224),

    "Validation Split":
        0.20,

    "Workers":
        2
}


for key, value in config.items():

    print(
        f"🔹 {key}: {value}"
    )


# ============================================================
# STEP 3: CHECK DATASET
# ============================================================

print("\n" + "=" * 70)
print("📂 STEP 2: CHECKING DATASET")
print("=" * 70)


if not os.path.exists(dataset_root):

    raise FileNotFoundError(
        f"""
❌ Dataset directory does not exist:

{dataset_root}

Please download the dataset using KaggleHub first.
"""
    )


print(
    f"✅ Dataset directory exists:\n{dataset_root}"
)


# ------------------------------------------------------------
# Find all image files recursively
# ------------------------------------------------------------

image_extensions = (
    ".png",
    ".jpg",
    ".jpeg",
    ".bmp",
    ".tif",
    ".tiff"
)


all_image_paths = []


for root, dirs, files in os.walk(dataset_root):

    for file in files:

        if file.lower().endswith(
            image_extensions
        ):

            all_image_paths.append(
                os.path.join(root, file)
            )


all_image_paths = sorted(
    all_image_paths
)


print(
    f"\n🖼️ Total images discovered: "
    f"{len(all_image_paths):,}"
)


if len(all_image_paths) == 0:

    raise RuntimeError(
        f"""
❌ No images were found inside:

{dataset_root}

Please check the KaggleHub download.
"""
    )


print("\n🔍 First 20 image paths:")

for path in all_image_paths[:20]:

    print(
        "   ",
        path
    )


# ============================================================
# STEP 4: IDENTIFY BHSIG260 STRUCTURE
# ============================================================

print("\n" + "=" * 70)
print("🔎 STEP 3: ANALYZING BHSIG260 DATASET STRUCTURE")
print("=" * 70)


# ------------------------------------------------------------
# Search for Bengali / Hindi folders
# ------------------------------------------------------------

language_folders = []


for root, dirs, files in os.walk(dataset_root):

    folder_name = os.path.basename(root).lower()

    if folder_name in [
        "bengali",
        "hindi",
        "bhsig260-bengali",
        "bhsig260-hindi"
    ]:

        language_folders.append(root)


print(
    f"Detected language folders: "
    f"{len(language_folders)}"
)


for folder in language_folders:

    print(
        "   📁",
        folder
    )


# ============================================================
# STEP 5: DATASET IMAGE METADATA
# ============================================================

def get_language_from_path(path):

    """
    Determine whether an image belongs to Bengali or Hindi.
    """

    path_lower = path.lower()

    if "bengali" in path_lower:

        return "bengali"

    if "hindi" in path_lower:

        return "hindi"

    return "unknown"


def get_signer_id(path):

    """
    Extract signer ID from the directory structure.

    BHSig260 is organized by signer folders.
    We use the directory immediately containing the image
    as the signer identifier when possible.
    """

    parent_dir = os.path.basename(
        os.path.dirname(path)
    )

    return parent_dir


# ============================================================
# STEP 6: DETECT GENUINE / FORGED
# ============================================================

def classify_signature(path):

    """
    Determine whether an image is genuine or forged.

    We inspect the filename and parent directory names.
    """

    text = path.lower()

    # Forged indicators
    forged_keywords = [
        "forg",
        "forged",
        "forgery",
        "forge",
        "fake"
    ]

    # Genuine indicators
    genuine_keywords = [
        "genuine",
        "original",
        "real"
    ]


    for keyword in forged_keywords:

        if keyword in text:

            return "forged"


    for keyword in genuine_keywords:

        if keyword in text:

            return "genuine"


    # --------------------------------------------------------
    # BHSig260 common filename patterns
    #
    # If the dataset uses a final G/F marker,
    # detect it here.
    # --------------------------------------------------------

    filename = os.path.basename(
        path
    ).lower()


    # Remove extension
    filename_without_ext = os.path.splitext(
        filename
    )[0]


    # Tokenize
    tokens = re.split(
        r"[_\-\s]+",
        filename_without_ext
    )


    for token in tokens:

        if token in [
            "g",
            "genuine"
        ]:

            return "genuine"


        if token in [
            "f",
            "forged",
            "forgery"
        ]:

            return "forged"


    return "unknown"


# ============================================================
# STEP 7: CREATE SIGNER-BASED IMAGE GROUPS
# ============================================================

print("\n" + "=" * 70)
print("👤 STEP 4: GROUPING IMAGES BY SIGNER")
print("=" * 70)


signer_images = {}


for image_path in all_image_paths:

    language = get_language_from_path(
        image_path
    )

    signer = get_signer_id(
        image_path
    )

    signature_type = classify_signature(
        image_path
    )


    if signature_type == "unknown":

        continue


    # Use language + signer as unique identity
    signer_key = (
        language,
        signer
    )


    if signer_key not in signer_images:

        signer_images[signer_key] = {
            "genuine": [],
            "forged": []
        }


    signer_images[
        signer_key
    ][signature_type].append(
        image_path
    )


print(
    f"✅ Signers detected: "
    f"{len(signer_images)}"
)


# ============================================================
# STEP 8: DISPLAY DATASET STATISTICS
# ============================================================

total_genuine = 0
total_forged = 0


for signer_key, data in signer_images.items():

    total_genuine += len(
        data["genuine"]
    )

    total_forged += len(
        data["forged"]
    )


print(
    f"   Genuine signatures: "
    f"{total_genuine:,}"
)

print(
    f"   Forged signatures: "
    f"{total_forged:,}"
)


# ============================================================
# IMPORTANT VALIDATION
# ============================================================

if len(signer_images) == 0:

    print("\n❌ No signer groups were detected.")

    print(
        "\nThe first 50 files are:"
    )

    for path in all_image_paths[:50]:

        print(path)


    raise RuntimeError(
        """
❌ Dataset structure could not be automatically
identified.

The file names/folders do not match the expected
BHSig260 structure.

Please inspect the paths printed above.
"""
    )


# ============================================================
# STEP 9: TRAIN / VALIDATION SPLIT
# ============================================================

print("\n" + "=" * 70)
print("✂️ STEP 5: CREATING SIGNER-BASED TRAIN/VALIDATION SPLIT")
print("=" * 70)


signer_keys = list(
    signer_images.keys()
)


random.shuffle(
    signer_keys
)


split_index = int(
    len(signer_keys)
    * (1 - config["Validation Split"])
)


train_signers = signer_keys[
    :split_index
]


val_signers = signer_keys[
    split_index:
]


print(
    f"Training signers: "
    f"{len(train_signers)}"
)

print(
    f"Validation signers: "
    f"{len(val_signers)}"
)


# ============================================================
# STEP 10: PAIR GENERATION
# ============================================================

def create_pairs(
    signer_list,
    max_positive_per_signer=100,
    max_negative_per_signer=100
):

    pairs = []
    labels = []


    for signer_key in signer_list:

        genuine = signer_images[
            signer_key
        ]["genuine"]

        forged = signer_images[
            signer_key
        ]["forged"]


        # ----------------------------------------------------
        # POSITIVE PAIRS
        # Genuine + Genuine
        # Label = 0
        # ----------------------------------------------------

        positive_pairs = []


        for i in range(
            len(genuine)
        ):

            for j in range(
                i + 1,
                len(genuine)
            ):

                positive_pairs.append(
                    (
                        genuine[i],
                        genuine[j]
                    )
                )


        random.shuffle(
            positive_pairs
        )


        positive_pairs = positive_pairs[
            :max_positive_per_signer
        ]


        for pair in positive_pairs:

            pairs.append(pair)

            labels.append(0.0)


        # ----------------------------------------------------
        # NEGATIVE PAIRS
        # Genuine + Forged
        # Label = 1
        # ----------------------------------------------------

        negative_pairs = []


        for genuine_path in genuine:

            for forged_path in forged:

                negative_pairs.append(
                    (
                        genuine_path,
                        forged_path
                    )
                )


        random.shuffle(
            negative_pairs
        )


        negative_pairs = negative_pairs[
            :max_negative_per_signer
        ]


        for pair in negative_pairs:

            pairs.append(pair)

            labels.append(1.0)


    return pairs, labels


# ============================================================
# CREATE TRAINING PAIRS
# ============================================================

train_pairs, train_labels = create_pairs(
    train_signers
)


# ============================================================
# CREATE VALIDATION PAIRS
# ============================================================

val_pairs, val_labels = create_pairs(
    val_signers
)


print(
    "\n📊 TRAINING PAIRS"
)

print(
    f"   Genuine-Genuine: "
    f"{train_labels.count(0.0):,}"
)

print(
    f"   Genuine-Forged: "
    f"{train_labels.count(1.0):,}"
)

print(
    f"   Total: "
    f"{len(train_pairs):,}"
)


print(
    "\n📊 VALIDATION PAIRS"
)

print(
    f"   Genuine-Genuine: "
    f"{val_labels.count(0.0):,}"
)

print(
    f"   Genuine-Forged: "
    f"{val_labels.count(1.0):,}"
)

print(
    f"   Total: "
    f"{len(val_pairs):,}"
)


if len(train_pairs) == 0:

    raise RuntimeError(
        """
❌ Training pairs = 0.

The dataset was found, but the genuine/forged
classification did not work correctly.
"""
    )


# ============================================================
# STEP 11: IMAGE TRANSFORMS
# ============================================================

print("\n" + "=" * 70)
print("🖼️ STEP 6: PREPARING IMAGE TRANSFORMS")
print("=" * 70)


train_transform = transforms.Compose([

    transforms.Resize(
        config["Image Resize Dimensions"]
    ),

    transforms.RandomRotation(
        degrees=5
    ),

    transforms.RandomAffine(
        degrees=0,
        translate=(0.03, 0.03),
        scale=(0.95, 1.05)
    ),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[
            0.485,
            0.456,
            0.406
        ],

        std=[
            0.229,
            0.224,
            0.225
        ]
    )
])


val_transform = transforms.Compose([

    transforms.Resize(
        config["Image Resize Dimensions"]
    ),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[
            0.485,
            0.456,
            0.406
        ],

        std=[
            0.229,
            0.224,
            0.225
        ]
    )
])


# ============================================================
# STEP 12: PYTORCH DATASET
# ============================================================

class SignaturePairDataset(Dataset):

    def __init__(
        self,
        pairs,
        labels,
        transform=None
    ):

        self.pairs = pairs
        self.labels = labels
        self.transform = transform


    def __len__(self):

        return len(
            self.pairs
        )


    def __getitem__(self, index):

        image1_path, image2_path = (
            self.pairs[index]
        )


        image1 = Image.open(
            image1_path
        ).convert("RGB")


        image2 = Image.open(
            image2_path
        ).convert("RGB")


        if self.transform:

            image1 = self.transform(
                image1
            )

            image2 = self.transform(
                image2
            )


        label = torch.tensor(
            self.labels[index],
            dtype=torch.float32
        )


        return (
            image1,
            image2,
            label
        )


# ============================================================
# STEP 13: CREATE DATA LOADERS
# ============================================================

train_dataset = SignaturePairDataset(
    train_pairs,
    train_labels,
    transform=train_transform
)


val_dataset = SignaturePairDataset(
    val_pairs,
    val_labels,
    transform=val_transform
)


train_loader = DataLoader(
    train_dataset,
    batch_size=config["Batch Size"],
    shuffle=True,
    num_workers=config["Workers"],
    pin_memory=torch.cuda.is_available()
)


val_loader = DataLoader(
    val_dataset,
    batch_size=config["Batch Size"],
    shuffle=False,
    num_workers=config["Workers"],
    pin_memory=torch.cuda.is_available()
)


print(
    "\n✅ DataLoaders created successfully."
)

print(
    f"Training batches: "
    f"{len(train_loader)}"
)

print(
    f"Validation batches: "
    f"{len(val_loader)}"
)


# ============================================================
# STEP 14: SIAMESE RESNET-18 MODEL
# ============================================================

print("\n" + "=" * 70)
print("🧠 STEP 7: BUILDING SIAMESE RESNET-18")
print("=" * 70)


class SiameseResNet(nn.Module):

    def __init__(
        self,
        embedding_dim=128
    ):

        super().__init__()


        # ----------------------------------------------------
        # Pretrained ResNet18
        # ----------------------------------------------------

        self.backbone = models.resnet18(
            weights=models.ResNet18_Weights.DEFAULT
        )


        num_features = (
            self.backbone.fc.in_features
        )


        # Remove classification layer
        self.backbone.fc = nn.Identity()


        # ----------------------------------------------------
        # Embedding head
        # ----------------------------------------------------

        self.fc_head = nn.Sequential(

            nn.Linear(
                num_features,
                512
            ),

            nn.BatchNorm1d(
                512
            ),

            nn.ReLU(
                inplace=True
            ),

            nn.Dropout(
                p=0.3
            ),

            nn.Linear(
                512,
                embedding_dim
            )
        )


    def forward_once(self, x):

        features = self.backbone(
            x
        )

        embedding = self.fc_head(
            features
        )

        # Normalize embedding
        embedding = nn.functional.normalize(
            embedding,
            p=2,
            dim=1
        )

        return embedding


    def forward(
        self,
        input1,
        input2
    ):

        output1 = self.forward_once(
            input1
        )

        output2 = self.forward_once(
            input2
        )

        return (
            output1,
            output2
        )


model = SiameseResNet(
    embedding_dim=config[
        "Embedding Dimension"
    ]
).to(device)


total_params = sum(
    p.numel()
    for p in model.parameters()
)


trainable_params = sum(
    p.numel()
    for p in model.parameters()
    if p.requires_grad
)


print(
    "✅ Model created successfully."
)

print(
    f"Total parameters: "
    f"{total_params:,}"
)

print(
    f"Trainable parameters: "
    f"{trainable_params:,}"
)


# ============================================================
# STEP 15: CONTRASTIVE LOSS
# ============================================================

print("\n" + "=" * 70)
print("🧪 STEP 8: LOSS FUNCTION & OPTIMIZER")
print("=" * 70)


class ContrastiveLoss(nn.Module):

    def __init__(
        self,
        margin=2.0
    ):

        super().__init__()

        self.margin = margin


    def forward(
        self,
        output1,
        output2,
        label
    ):

        distance = nn.functional.pairwise_distance(
            output1,
            output2
        )


        positive_loss = (
            (1 - label)
            * torch.pow(
                distance,
                2
            )
        )


        negative_loss = (
            label
            * torch.pow(
                torch.clamp(
                    self.margin - distance,
                    min=0.0
                ),
                2
            )
        )


        loss = torch.mean(
            positive_loss
            + negative_loss
        )


        return loss


criterion = ContrastiveLoss(
    margin=config[
        "Contrastive Margin"
    ]
)


optimizer = optim.Adam(
    model.parameters(),
    lr=config["Learning Rate"],
    weight_decay=config["Weight Decay"]
)


# ============================================================
# STEP 16: VALIDATION FUNCTION
# ============================================================

def evaluate_model(
    model,
    data_loader,
    criterion,
    device,
    threshold=1.0
):

    model.eval()


    total_loss = 0.0
    correct = 0
    total = 0


    with torch.no_grad():

        for img1, img2, label in data_loader:

            img1 = img1.to(
                device,
                non_blocking=True
            )

            img2 = img2.to(
                device,
                non_blocking=True
            )

            label = label.to(
                device,
                non_blocking=True
            )


            output1, output2 = model(
                img1,
                img2
            )


            loss = criterion(
                output1,
                output2,
                label
            )


            total_loss += (
                loss.item()
                * img1.size(0)
            )


            distance = nn.functional.pairwise_distance(
                output1,
                output2
            )


            # Smaller distance = same signature
            predicted = (
                distance > threshold
            ).float()


            correct += (
                predicted == label
            ).sum().item()


            total += label.size(0)


    avg_loss = (
        total_loss / total
        if total > 0
        else 0
    )


    accuracy = (
        correct / total
        if total > 0
        else 0
    )


    return avg_loss, accuracy


# ============================================================
# STEP 17: TRAINING
# ============================================================

print("\n" + "=" * 70)
print("🏋️ STEP 9: STARTING TRAINING")
print("=" * 70)


best_val_loss = float(
    "inf"
)


for epoch in range(
    config["Training Epochs"]
):

    # --------------------------------------------------------
    # TRAIN
    # --------------------------------------------------------

    model.train()

    running_loss = 0.0


    print(
        f"\n🎬 Epoch "
        f"[{epoch + 1}/"
        f"{config['Training Epochs']}]"
    )


    for batch_idx, (
        img1,
        img2,
        label
    ) in enumerate(
        train_loader
    ):

        img1 = img1.to(
            device,
            non_blocking=True
        )

        img2 = img2.to(
            device,
            non_blocking=True
        )

        label = label.to(
            device,
            non_blocking=True
        )


        optimizer.zero_grad()


        output1, output2 = model(
            img1,
            img2
        )


        loss = criterion(
            output1,
            output2,
            label
        )


        loss.backward()


        optimizer.step()


        running_loss += (
            loss.item()
        )


        if (
            (batch_idx + 1) % 20 == 0
            or
            (batch_idx + 1)
            == len(train_loader)
        ):

            print(
                f"⏱️ Batch "
                f"[{batch_idx + 1}/"
                f"{len(train_loader)}] "
                f"Loss: {loss.item():.4f}"
            )


    train_loss = (
        running_loss
        / len(train_loader)
    )


    # --------------------------------------------------------
    # VALIDATION
    # --------------------------------------------------------

    val_loss, val_accuracy = evaluate_model(
        model,
        val_loader,
        criterion,
        device,
        threshold=1.0
    )


    print(
        f"\n📉 Train Loss: "
        f"{train_loss:.4f}"
    )

    print(
        f"📊 Validation Loss: "
        f"{val_loss:.4f}"
    )

    print(
        f"🎯 Validation Accuracy: "
        f"{val_accuracy * 100:.2f}%"
    )


    # --------------------------------------------------------
    # SAVE BEST MODEL
    # --------------------------------------------------------

    if val_loss < best_val_loss:

        best_val_loss = val_loss


        torch.save(
            model.state_dict(),
            "best_siamese_resnet_signature.pth"
        )


        print(
            "💾 Best model saved."
        )


# ============================================================
# STEP 18: SAVE FINAL MODEL
# ============================================================

print("\n" + "=" * 70)
print("💾 STEP 10: SAVING FINAL MODEL")
print("=" * 70)


final_model_path = (
    "siamese_resnet_signature_final.pth"
)


torch.save(
    model.state_dict(),
    final_model_path
)


print(
    f"✅ Final model saved as:\n"
    f"{final_model_path}"
)


print(
    "\n🎉 TRAINING COMPLETED SUCCESSFULLY!"
)


print(
    "\nNext step:"
)

print(
    "Use the saved Siamese model to compare "
    "two signature images using Euclidean distance."
)

# ============================================================
# RANDOM SIGNATURE VERIFICATION TEST
# ============================================================

import os
import random
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.models as models
from torchvision import transforms
from PIL import Image


# ============================================================
# SETTINGS
# ============================================================

MODEL_PATH = "siamese_resnet_signature_final.pth"

DATASET_ROOT = (
    "/root/.cache/kagglehub/datasets/"
    "ishanikathuria/handwritten-signature-datasets/"
    "versions/3/CEDAR/CEDAR"
)

# Temporary threshold
THRESHOLD = 1.0

# For reproducible random selection
random.seed(42)


# ============================================================
# DEVICE
# ============================================================

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)


# ============================================================
# MODEL
# ============================================================

class SiameseResNet(nn.Module):

    def __init__(self):

        super().__init__()

        # ResNet18 backbone
        self.backbone = models.resnet18(weights=None)

        num_features = self.backbone.fc.in_features

        # Remove original ResNet classifier
        self.backbone.fc = nn.Identity()

        # IMPORTANT:
        # This matches your trained model
        self.fc_head = nn.Sequential(
            nn.Linear(num_features, 512),
            nn.BatchNorm1d(512),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(512, 128)
        )


    def forward_once(self, x):

        features = self.backbone(x)

        embedding = self.fc_head(features)

        embedding = F.normalize(
            embedding,
            p=2,
            dim=1
        )

        return embedding


# ============================================================
# LOAD MODEL
# ============================================================

model = SiameseResNet().to(device)

checkpoint = torch.load(
    MODEL_PATH,
    map_location=device
)

# Your saved file is a state_dict
if isinstance(checkpoint, dict) and "model_state_dict" in checkpoint:

    state_dict = checkpoint["model_state_dict"]

else:

    state_dict = checkpoint


model.load_state_dict(state_dict)

model.eval()


# ============================================================
# IMAGE TRANSFORMATION
# ============================================================

transform = transforms.Compose([

    transforms.Resize((224, 224)),

    transforms.Grayscale(
        num_output_channels=3
    ),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])


# ============================================================
# FIND CEDAR SIGNATURES
# ============================================================

writers = {}

for writer_id in os.listdir(DATASET_ROOT):

    writer_path = os.path.join(
        DATASET_ROOT,
        writer_id
    )

    if not os.path.isdir(writer_path):
        continue

    genuine = []
    forged = []

    for filename in os.listdir(writer_path):

        filepath = os.path.join(
            writer_path,
            filename
        )

        if not os.path.isfile(filepath):
            continue

        filename_lower = filename.lower()

        # Genuine CEDAR files
        if filename_lower.startswith("original_"):

            genuine.append(filepath)

        # Forged CEDAR files
        elif filename_lower.startswith("forgeries_"):

            forged.append(filepath)


    # Only keep writers having both types
    if len(genuine) >= 2 and len(forged) >= 1:

        writers[writer_id] = {
            "genuine": genuine,
            "forged": forged
        }


# ============================================================
# CHECK DATASET
# ============================================================

if len(writers) < 2:

    raise RuntimeError(
        "Not enough writers found in the CEDAR dataset."
    )


# ============================================================
# EMBEDDING FUNCTION
# ============================================================

def get_embedding(image_path):

    image = Image.open(
        image_path
    ).convert("RGB")

    image = transform(image)

    image = image.unsqueeze(0).to(device)

    with torch.no_grad():

        embedding = model.forward_once(image)

    return embedding


# ============================================================
# DISTANCE FUNCTION
# ============================================================

def get_distance(image1, image2):

    embedding1 = get_embedding(image1)

    embedding2 = get_embedding(image2)

    distance = torch.norm(
        embedding1 - embedding2,
        p=2
    ).item()

    return distance


# ============================================================
# RANDOM WRITER SELECTION
# ============================================================

writer_ids = list(writers.keys())


# ------------------------------------------------------------
# TEST 1
# SAME WRITER - GENUINE vs GENUINE
# ------------------------------------------------------------

writer_same = random.choice(writer_ids)

genuine_images = writers[
    writer_same
]["genuine"]

image1_test1, image2_test1 = random.sample(
    genuine_images,
    2
)

distance1 = get_distance(
    image1_test1,
    image2_test1
)

prediction1 = (
    "SAME WRITER"
    if distance1 <= THRESHOLD
    else "DIFFERENT WRITER"
)

expected1 = "SAME WRITER"

correct1 = prediction1 == expected1


# ------------------------------------------------------------
# TEST 2
# SAME WRITER - GENUINE vs FORGED
# ------------------------------------------------------------

writer_forged = random.choice(writer_ids)

genuine_test2 = random.choice(
    writers[writer_forged]["genuine"]
)

forged_test2 = random.choice(
    writers[writer_forged]["forged"]
)

distance2 = get_distance(
    genuine_test2,
    forged_test2
)

prediction2 = (
    "SAME WRITER"
    if distance2 <= THRESHOLD
    else "DIFFERENT WRITER"
)

expected2 = "DIFFERENT WRITER"

correct2 = prediction2 == expected2


# ------------------------------------------------------------
# TEST 3
# DIFFERENT WRITERS - GENUINE vs GENUINE
# ------------------------------------------------------------

writer_a, writer_b = random.sample(
    writer_ids,
    2
)

image_a = random.choice(
    writers[writer_a]["genuine"]
)

image_b = random.choice(
    writers[writer_b]["genuine"]
)

distance3 = get_distance(
    image_a,
    image_b
)

prediction3 = (
    "SAME WRITER"
    if distance3 <= THRESHOLD
    else "DIFFERENT WRITER"
)

expected3 = "DIFFERENT WRITER"

correct3 = prediction3 == expected3


# ============================================================
# FINAL RESULTS ONLY
# ============================================================

print()
print("=" * 60)
print("SIGNATURE VERIFICATION RESULTS")
print("=" * 60)

print(
    f"\nTest 1 - Same Writer Genuine vs Genuine"
)

print(
    f"Writer: {writer_same}"
)

print(
    f"Distance: {distance1:.4f}"
)

print(
    f"Prediction: {prediction1}"
)

print(
    f"Expected: {expected1}"
)

print(
    "Result: " + ("CORRECT ✅" if correct1 else "WRONG ❌")
)


print(
    f"\nTest 2 - Genuine vs Forged"
)

print(
    f"Writer: {writer_forged}"
)

print(
    f"Distance: {distance2:.4f}"
)

print(
    f"Prediction: {prediction2}"
)

print(
    f"Expected: {expected2}"
)

print(
    "Result: " + ("CORRECT ✅" if correct2 else "WRONG ❌")
)


print(
    f"\nTest 3 - Different Writers Genuine vs Genuine"
)

print(
    f"Writers: {writer_a} vs {writer_b}"
)

print(
    f"Distance: {distance3:.4f}"
)

print(
    f"Prediction: {prediction3}"
)

print(
    f"Expected: {expected3}"
)

print(
    "Result: " + ("CORRECT ✅" if correct3 else "WRONG ❌")
)


# ============================================================
# OVERALL
# ============================================================

total_correct = (
    int(correct1)
    + int(correct2)
    + int(correct3)
)

print("\n" + "=" * 60)

print(
    f"Overall: {total_correct}/3 tests correct"
)

print(
    f"Threshold: {THRESHOLD:.2f}"
)

print("=" * 60)